name: python cdk deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: install web dependencies
      run: npm ci
      working-directory: ./web

    - name: build web app
      run: npm run build --if-present
      working-directory: ./web

    - name: install AWS CDK
      run: npm i -g aws-cdk

    - name: build AWS CDK
      run: npm run build --if-present
      working-directory: ./backend

    - name: install deployment dependencies
      run: pip install -r requirements.txt
      working-directory: ./py-webdepl

    - name: cdk synth
      run: cdk synth
      working-directory: ./py-webdepl

    - name: cdk deploy
      run: cdk deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      working-directory: ./py-webdepl
